#!/usr/bin/env bash
# Start buyers and generate per-container config_service_discovery_v2.sh
# that points --geom-url to the eth0 IP of a given bootstrap container.
#
# Usage:
#   ./start_buyer.sh --bootstrap clab-century-serf7
#   ./start_buyer.sh --bootstrap clab-century-serf7 --prefix clab-century-buyer --start 1 --end 10
#
# Flags:
#   --bootstrap <name>   (REQUIRED) container that hosts the geometry API on eth0:4040
#   --prefix <pfx>       default: clab-century-serf
#   --start <N>          default: 1
#   --end <M>            default: 10
#   --delay <secs>       default: 5
#   --container-dir <dir> default: /opt/serfapp
#   --buyer-script <path> default: ./config_buyer.sh
#   --disc-script <path>  default: ./config_service_discovery_v2.sh
#   --geom-port <port>   default: 4040
#   --geom-path <path>   default: /cluster-status
#
set -euo pipefail

# -------- Defaults --------
BOOTSTRAP="clab-century-serf1"
PREFIX="clab-century-serf"
START=1
END=1
DELAY_SECS=5
CONTAINER_APP_DIR="/opt/serfapp"
BUYER_SCRIPT="config_buyer.sh"
DISC_SCRIPT="config_service_discovery_v6.sh"
GEOM_PORT=4040
GEOM_PATH="/cluster-status"

# -------- Flags --------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --bootstrap) BOOTSTRAP="$2"; shift 2;;
    --prefix) PREFIX="$2"; shift 2;;
    --start) START="$2"; shift 2;;
    --end) END="$2"; shift 2;;
    --delay|--sleep) DELAY_SECS="$2"; shift 2;;
    --container-dir|--dir) CONTAINER_APP_DIR="$2"; shift 2;;
    --buyer-script) BUYER_SCRIPT="$2"; shift 2;;
    --disc-script|--discovery-script) DISC_SCRIPT="$2"; shift 2;;
    --geom-port) GEOM_PORT="$2"; shift 2;;
    --geom-path) GEOM_PATH="$2"; shift 2;;
    --help|-h)
      grep '^#' "$0" | sed -e 's/^# \{0,1\}//'
      exit 0;;
    *)
      echo "[ERROR] Unknown flag: $1" >&2; exit 1;;
  esac
done

log()  { echo -e "[\e[1mBUYER\e[0m] $*"; }
warn() { echo -e "[\e[33mWARN\e[0m] $*" >&2; }
err()  { echo -e "[\e[31mERROR\e[0m] $*" >&2; }
require_cmd() { command -v "$1" >/dev/null 2>&1 || { err "Required command '$1' not found."; exit 1; }; }
container_name() { echo "${PREFIX}$1"; }

require_cmd docker

if [[ -z "$BOOTSTRAP" ]]; then
  err "You must specify --bootstrap <container-name> (the node hosting the geometry API)."
  exit 1
fi

# -------- Resolve bootstrap eth0 IP --------
log "Reading eth0 IP from bootstrap container: $BOOTSTRAP"
if ! docker inspect "$BOOTSTRAP" >/dev/null 2>&1; then
  err "Bootstrap container '$BOOTSTRAP' not found."
  exit 1
fi

BOOTSTRAP_IP="$(docker exec -u root "$BOOTSTRAP" bash -lc \
  "ip -4 -o addr show dev eth0 2>/dev/null | awk '{print \$4}' | cut -d/ -f1 | head -n1")"

if [[ -z "$BOOTSTRAP_IP" ]]; then
  err "Could not determine eth0 IPv4 address inside '$BOOTSTRAP'."
  err "Ensure 'ip' is available in the container and eth0 is present."
  exit 1
fi

GEOM_URL="http://${BOOTSTRAP_IP}:${GEOM_PORT}${GEOM_PATH}"
log "Using GEOM_URL = $GEOM_URL"

# -------- Helpers --------
file_exists_in_container() {
  local name="$1"; local path="$2"
  docker exec -u root "$name" bash -lc "[ -e '$path' ]"
}

run_bg_in_container_dir() {
  local name="$1"; shift
  local dir="$1"; shift
  local cmd="$*"
  docker exec -u root "$name" bash -lc "mkdir -p /var/log"
  docker exec -u root -d "$name" bash -lc "cd '$dir' && { $cmd >>/var/log/serfapp_bg.log 2>&1 & }"
}

# Extract rpc_addr from node.json using python inside container (fallback: 127.0.0.1:7373)
get_rpc_addr_in() {
  local name="$1"
  docker exec -u root "$name" bash -lc \
    "python3 - <<'PY'
import json,sys,os
p='/opt/serfapp/node.json'
try:
    d=json.load(open(p))
    print(d.get('rpc_addr','127.0.0.1:7373'))
except Exception:
    print('127.0.0.1:7373')
PY"
}

# Create /opt/serfapp/config_service_discovery_v2.sh inside the container
write_discovery_config_in() {
  local name="$1"
  local rpc_addr="$2"
  local target="${CONTAINER_APP_DIR}/${DISC_SCRIPT}"

  docker exec -u root "$name" bash -lc "mkdir -p '$CONTAINER_APP_DIR'"

  docker exec -u root -i "$name" bash -lc "cat > '$target'" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "\${BASH_SOURCE[0]}")"

# Auto-generated by start_buyer.sh
# NOTE: --query-node intentionally omitted. Python will be updated to read node_name from node.json.
python3 service_discovery_v5.py \\
  --geom-url '${GEOM_URL}' \\
  --rtt-threshold-ms 12 \\
  --rpc-addr '${rpc_addr}' --timeout-s 8 \\
  --sort score_per_cpu --limit 10 \\
  --http-serve --http-host 0.0.0.0 --http-port 4041 --http-path /hilbert-output \\
  --buyer-url http://127.0.0.1:8090/buyer
EOF

  docker exec -u root "$name" bash -lc "chmod +x '$target'"
  log "Wrote ${target} in ${name}"
}

# -------- Main loop --------
for i in $(seq "$START" "$END"); do
  name="$(container_name "$i")"
  log "Target: $name"

  # build config in container
  RPC_ADDR="$(get_rpc_addr_in "$name" | tr -d '\r')"
  write_discovery_config_in "$name" "$RPC_ADDR"

  # Buyer script
  if file_exists_in_container "$name" "${CONTAINER_APP_DIR}/${BUYER_SCRIPT}"; then
    log "Launching $BUYER_SCRIPT in $name (detached)…"
    run_bg_in_container_dir "$name" "$CONTAINER_APP_DIR" "bash '${BUYER_SCRIPT}'"
  else
    warn "Missing ${CONTAINER_APP_DIR}/${BUYER_SCRIPT} in $name; skipping buyer."
  fi

  # Delay
  log "Sleeping ${DELAY_SECS}s before discovery in $name…"
  sleep "${DELAY_SECS}"

  # Discovery script
  if file_exists_in_container "$name" "${CONTAINER_APP_DIR}/${DISC_SCRIPT}"; then
    log "Launching $DISC_SCRIPT in $name (detached)…"
    run_bg_in_container_dir "$name" "$CONTAINER_APP_DIR" "bash '${DISC_SCRIPT}'"
  else
    warn "Missing ${CONTAINER_APP_DIR}/${DISC_SCRIPT} in $name (unexpected)."
  fi

  log "Done with $name. Tail logs: docker exec -it $name tail -f /var/log/serfapp_bg.log"
done

log "All buyer + discovery scripts launched."
