apiVersion: v1
kind: Node
metadata:
  name: kwok-node-0
  labels:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    type: kwok
  annotations:
    kwok.x-k8s.io/node: "fake"
    # Optional: feed metrics-usage addon
    kwok.x-k8s.io/usage-cpu: "200m"
    kwok.x-k8s.io/usage-memory: "256Mi"
spec:
  taints:
    - key: kwok.x-k8s.io/node
      value: fake
      effect: NoSchedule
